language: python
dist: xenial
python:
  - "3.7"
  - "3.4"
  - "2.7"

stages:
  - lint
  - test
  - name: deploy
    if: tag IS present

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

git:
  # Allows `git describe` access all tags
  depth: false

before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install -v
script:
  - poetry run pytest -v --cov=hammlet

jobs:
  include:
    - stage: lint
      python: "3.7"
      before_install:
        - pip install pre-commit
      install:
        - pre-commit install
      script:
        - pre-commit run --all-files

    - stage: deploy
      python: "3.7"
      script: skip
      before_deploy:
        # - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
      deploy:
        provider: script
        script:
          - make release
        skip_cleanup: true
        on:
          tags: true
