[tool.black]
line-length = 88
target-version = ['py27']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | dist
  | build
  | _build
  | buck-out

  # project-specific
  | data
)/
'''

[build-system]
requires = ["setuptools", "wheel"]
